name: CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Install checkers
        run: sudo apt update ; sudo apt-get install -y clang-tidy clang-format cppcheck ninja-build python3-pip build-essential cmake ; pip install --user cpplint


      - name: Проверка
        run: .github/lint.sh

  build-and-test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Install GCC
        run: sudo apt update ; sudo apt-get install -y build-essential cmake

      - name: Компиляция
        run: mkdir build ; cd build ; cmake .. ; make

      - name: Тестирование
        run: cd build ; ./graph_server & ./graph_test